#!/usr/bin/python3
"""Module that factorize as many numbers as possible
 into a product of two smaller numbers."""

import sys

def factorize(num):
    for i in range(2, num):
        if num % i == 0:
            return i, num // i
    return None

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

with open(sys.argv[1], "r") as f:
    for line in f:
        num = int(line.strip())
        factors = factorize(num)
        if factors is not None:
            print("{}={}*{}".format(num, factors[0], factors[1]))
